# An installed version alone does not establish Freac's offset-join adaptation.
# Validate the build receipt even for direct CMake users, before linking.
function(verify_freac_sdk)
  set(sdk "${OpenCASCADE_INSTALL_PREFIX}")
  if(NOT EXISTS "${sdk}/.freac-sdk.json")
    message(FATAL_ERROR "OCCT requires an adapted Freac SDK receipt. Run npm run setup:kernel without OCCT_ROOT.")
  endif()
  get_filename_component(root "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/../.." ABSOLUTE)
  set(inputs "")
  foreach(path scripts/occt-recipe.json scripts/setup-kernel.mjs scripts/occt-source.mjs scripts/sdk-provenance.mjs scripts/native-inputs.mjs native/kernel/verify-sdk.cmake)
    file(SHA256 "${root}/${path}" hash)
    string(APPEND inputs "${path}:${hash}\n")
  endforeach()
  string(SHA256 expected_recipe "${inputs}")
  file(READ "${sdk}/.freac-sdk.json" receipt)
  string(JSON schema GET "${receipt}" schema)
  string(JSON recipe GET "${receipt}" recipe)
  if(NOT schema EQUAL 1 OR NOT recipe STREQUAL expected_recipe)
    message(FATAL_ERROR "OCCT SDK recipe does not match this Freac checkout; rebuild with setup:kernel")
  endif()
  string(JSON system GET "${receipt}" settings system)
  string(JSON architecture GET "${receipt}" settings architecture)
  string(JSON target GET "${receipt}" settings deploymentTarget)
  set(expected_arch "${CMAKE_SYSTEM_PROCESSOR}")
  if(APPLE AND CMAKE_OSX_ARCHITECTURES)
    set(expected_arch "${CMAKE_OSX_ARCHITECTURES}")
  elseif(expected_arch MATCHES "^(AMD64|amd64|x64)$")
    set(expected_arch x86_64)
  elseif(expected_arch STREQUAL "aarch64")
    set(expected_arch arm64)
  endif()
  set(expected_target "")
  if(APPLE)
    set(expected_target "${CMAKE_OSX_DEPLOYMENT_TARGET}")
  endif()
  if(NOT system STREQUAL CMAKE_SYSTEM_NAME OR NOT architecture STREQUAL expected_arch OR NOT target STREQUAL expected_target)
    message(FATAL_ERROR "OCCT SDK platform, architecture or deployment target differs from the calculator")
  endif()
  string(JSON expected_manifest GET "${receipt}" filesHash)
  file(SHA256 "${sdk}/.freac-sdk-files" actual_manifest)
  if(NOT actual_manifest STREQUAL expected_manifest)
    message(FATAL_ERROR "OCCT SDK file manifest differs from its build receipt")
  endif()
  file(STRINGS "${sdk}/.freac-sdk-files" files)
  if(NOT files)
    message(FATAL_ERROR "OCCT SDK receipt has no installed files")
  endif()
  foreach(entry IN LISTS files)
    string(SUBSTRING "${entry}" 0 64 expected)
    string(SUBSTRING "${entry}" 65 -1 path)
    if(IS_ABSOLUTE "${path}" OR path MATCHES "(^|/)\.\.(/|$)" OR NOT EXISTS "${sdk}/${path}")
      message(FATAL_ERROR "Invalid/missing OCCT SDK receipt file: ${path}")
    endif()
    file(SHA256 "${sdk}/${path}" actual)
    if(NOT actual STREQUAL expected)
      message(FATAL_ERROR "OCCT SDK file differs from its build receipt: ${path}")
    endif()
  endforeach()
endfunction()
