import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { launchElectron } from "./native-documents.mjs";
import { arcRoute } from "./ui-arc.mjs";
import { arcLinkRoute } from "./ui-arc-links.mjs";
import { autoUnionRoute } from "./ui-auto-union.mjs";
import { backendPersistence } from "./ui-backend.mjs";
import { bezierRoute } from "./ui-bezier.mjs";
import { blendEditRoute } from "./ui-blend-edit.mjs";
import { bodyAnchorRoute } from "./ui-body-anchor.mjs";
import { bodyArchiveRoute } from "./ui-body-archive.mjs";
import { bodyBooleanRoute } from "./ui-body-boolean.mjs";
import { bodyChamferRoute } from "./ui-body-chamfer.mjs";
import { bodyEdgesRoute } from "./ui-body-edges.mjs";
import { bodyFilletRoute } from "./ui-body-fillet.mjs";
import { bodyMoveRoute, bodySnapRoute } from "./ui-body-move.mjs";
import { booleanTargetsRoute } from "./ui-boolean-targets.mjs";
import { constrainedBowRoute } from "./ui-bow-constraints.mjs";
import { bowDirectionRoute } from "./ui-bow-direction.mjs";
import { tangentBowRoute } from "./ui-bow-tangent.mjs";
import { cameraRoute } from "./ui-camera.mjs";
import { circleRoute } from "./ui-circle.mjs";
import { circularTangencyRoute } from "./ui-circular-tangency.mjs";
import { cleanupRoute } from "./ui-cleanup.mjs";
import { coincidenceRoute } from "./ui-coincident.mjs";
import { concentricRoute } from "./ui-concentric.mjs";
import { constraintPanelRoute } from "./ui-constraint-panel.mjs";
import { cornerAngleRoute } from "./ui-corner-angle.mjs";
import { cornerFilletRoute } from "./ui-corner-fillet.mjs";
import { curvedRegionRoute } from "./ui-curved-regions.mjs";
import { curvedRoundingRoute } from "./ui-curved-rounding.mjs";
import { drawingLinksRoute } from "./ui-drawing-links.mjs";
import { edgeCases } from "./ui-edge-cases.mjs";
import { edgeChainRoute } from "./ui-edge-chain.mjs";
import { editIntentRoute } from "./ui-edit-intent.mjs";
import { entitiesRoute } from "./ui-entities.mjs";
import { entityDeleteRoute } from "./ui-entity-delete.mjs";
import { extrudeRoute, extrusionGestureRoute } from "./ui-extrude.mjs";
import { extrudeDraftRoute } from "./ui-extrude-draft.mjs";
import { extrusionWidgetRoute } from "./ui-extrude-widget.mjs";
import { faceOffsetRoute } from "./ui-face-offset.mjs";
import { fillRoute } from "./ui-fill.mjs";
import { filletLossRoute, filletRoute } from "./ui-fillet.mjs";
import { filletConsumptionRoute } from "./ui-fillet-consumption.mjs";
import { filletGuideRoute } from "./ui-fillet-guide.mjs";
import { interactionLifecycleRoute } from "./ui-interaction-lifecycle.mjs";
import { jointBowRoute } from "./ui-joint-bow.mjs";
import { lineRoute } from "./ui-line.mjs";
import { lockRoute } from "./ui-locks.mjs";
import { loopOffsetRoute } from "./ui-loop-offset.mjs";
import { modelToolsRoute } from "./ui-model-tools.mjs";
import { modelingRoute } from "./ui-modeling.mjs";
import { moveToolRoute } from "./ui-move-tool.mjs";
import {
  movementGeometrySnapRoute,
  movementSnappingRoute,
  rectangleEdgeRoute,
  rotatedEdgeRoute,
} from "./ui-movement-snapping.mjs";
import { offsetRoute } from "./ui-offset.mjs";
import { offsetChainRoute } from "./ui-offset-chain.mjs";
import { offsetContactRoute } from "./ui-offset-contact.mjs";
import { pointChoiceRoute } from "./ui-point-choice.mjs";
import { pointEdgeRoute } from "./ui-point-edge.mjs";
import { pointIntentRoute } from "./ui-point-intent.mjs";
import { circleLinkRoute, pointLinkRoute } from "./ui-point-links.mjs";
import { projectionRoute } from "./ui-projection.mjs";
import { projectionFacesRoute } from "./ui-projection-faces.mjs";
import { rectangleRoute } from "./ui-rectangle.mjs";
import { rectangleBowRoute } from "./ui-rectangle-bow.mjs";
import { relationRoute } from "./ui-relations.mjs";
import { revolveRoute } from "./ui-revolve.mjs";
import { revolveSolidRoute } from "./ui-revolve-solid.mjs";
import { screwUnionRoute } from "./ui-screw-union.mjs";
import { selectionRoute } from "./ui-selection.mjs";
import { solidFacesRoute } from "./ui-solid-faces.mjs";
import { tangencyRoute } from "./ui-tangency.mjs";
import { tangentJunctionRoute } from "./ui-tangent-junction.mjs";
import { transformRoute } from "./ui-transform.mjs";
import { trimCircleRoute, trimLineRoute } from "./ui-trim.mjs";
import { trimArcRoute } from "./ui-trim-arcs.mjs";
import { trimConstraintRoute } from "./ui-trim-constraints.mjs";
import { typedSelectionRoute } from "./ui-typed-selection.mjs";
import { useEdgeRoute, useLineEdgeRoute } from "./ui-use-edge.mjs";
import { widgetNavigationRoute } from "./ui-widget-navigation.mjs";

await mkdir(".cache/sketch-review", { recursive: true });
const app = await launchElectron({ args: ["."], env: { ...process.env, FREAC_TEST_HIDDEN: "1" } });
try {
  const page = await app.firstWindow();
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.getByRole("button", { name: "Sketch on XY" }).click();
  await page.getByRole("status").filter({ hasText: "XY sketch" }).waitFor();
  assert.equal(
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].isVisible()),
    false,
  );
  assert.equal(await page.evaluate(() => typeof window.require), "undefined");
  await bowDirectionRoute(page, "electron");
  await modelingRoute(page, "electron");
  await entityDeleteRoute(page, "electron");
  await modelToolsRoute(page, "electron");
  await extrudeRoute(page, "electron", app);
  await extrusionGestureRoute(page);
  await booleanTargetsRoute(page);
  await useEdgeRoute(page, "electron");
  await useLineEdgeRoute(page);
  await solidFacesRoute(page, "electron");
  await jointBowRoute(page, "electron");
  await constraintPanelRoute(page, "electron");
  await interactionLifecycleRoute(page, "electron");
  await editIntentRoute(page, "electron");
  await typedSelectionRoute(page, "electron");
  await drawingLinksRoute(page, "electron");
  await pointEdgeRoute(page, "electron");
  await moveToolRoute(page, "electron");
  await pointLinkRoute(page, "electron");
  await circleLinkRoute(page, "electron");
  await arcLinkRoute(page, "electron");
  await coincidenceRoute(page, "electron");
  await cornerAngleRoute(page, "electron");
  await concentricRoute(page, "electron");
  await tangencyRoute(page, "electron");
  await circularTangencyRoute(page, "electron");
  await tangentJunctionRoute(page, "electron");
  await filletGuideRoute(page, "electron");
  await filletConsumptionRoute(page, "electron");
  await curvedRoundingRoute(page, "electron");
  await cornerFilletRoute(page, "electron");
  await filletRoute(page, "electron");
  await filletLossRoute(page, "electron");
  await trimLineRoute(page, "electron");
  await trimCircleRoute(page, "electron");
  await trimConstraintRoute(page, "electron");
  await trimArcRoute(page, "electron");
  await relationRoute(page, "electron");
  await lockRoute(page, "electron");
  await extrusionWidgetRoute(page, "electron");
  await bodyEdgesRoute(page, "electron");
  await bodyFilletRoute(page, "electron", app);
  await bodyChamferRoute(page, "electron", app);
  await edgeChainRoute(page, "electron");
  await faceOffsetRoute(page, "electron", app);
  await blendEditRoute(page, "electron");
  await offsetChainRoute(page, "electron");
  await offsetContactRoute(page, "electron", app);
  await revolveRoute(page, "electron", app);
  await revolveSolidRoute(page, "electron");
  await screwUnionRoute(page, "electron", app);
  await bodyBooleanRoute(page, "electron", app);
  await cleanupRoute(page, "electron", app);
  await autoUnionRoute(page, "electron");
  await extrudeDraftRoute(page, "electron", app);
  await bodyMoveRoute(page, "electron");
  await bodySnapRoute(page, "electron");
  await bodyAnchorRoute(page, "electron");
  await widgetNavigationRoute(page, "electron");
  await bodyArchiveRoute(page, "electron", app);
  await entitiesRoute(page, "electron");
  await cameraRoute(page, "electron");
  await bezierRoute(page, "electron");
  await projectionRoute(page, "electron", app);
  await projectionFacesRoute(page, "electron");
  await arcRoute(page, "electron");
  await pointChoiceRoute(page, "electron");
  await circleRoute(page, "electron");
  await curvedRegionRoute(page, "electron");
  await rectangleBowRoute(page, "electron");
  await constrainedBowRoute(page, "electron");
  await tangentBowRoute(page, "electron");
  await rectangleRoute(page, "electron");
  await movementSnappingRoute(page, "electron");
  await movementGeometrySnapRoute(page, "electron");
  await rectangleEdgeRoute(page, "electron");
  await rotatedEdgeRoute(page, "electron");
  await lineRoute(page, "electron");
  await pointIntentRoute(page, "electron");
  await fillRoute(page, "electron");
  await selectionRoute(page, "electron");
  await transformRoute(page, "electron");
  await offsetRoute(page, "electron");
  await loopOffsetRoute(page, "electron");
  await edgeCases(page, "electron");
  await backendPersistence(page, "electron");
  assert.deepEqual(errors, []);
  console.log("Hidden Electron: built renderer, plane entry and sandbox passed");
} finally {
  await app.close();
}
