cmake_minimum_required(VERSION 3.20)
project(makeshift_host LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_executable(makeshift-agent-scope agent-scope.cpp)
if(APPLE)
  target_link_libraries(makeshift-agent-scope PRIVATE proc)
endif()
set_target_properties(makeshift-agent-scope PROPERTIES RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
foreach(config Debug Release RelWithDebInfo MinSizeRel)
  string(TOUPPER ${config} config_upper)
  set_target_properties(makeshift-agent-scope PROPERTIES RUNTIME_OUTPUT_DIRECTORY_${config_upper} ${CMAKE_BINARY_DIR}/bin)
endforeach()
